import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: 101,
    firstName: "Ted",
    lastName: "Lasso",
    username: "tedlasso",
    password: "tedlasso123",
    profileImg: "https://i.postimg.cc/G2Q8d9s7/ted.png",
    backgroundImg: "https://i.postimg.cc/59ndTr3q/ted-henry.jpg",
    bio: "Be a goldfish.",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    followers: [
      {
        _id: 102,
        firstName: "Rebecca",
        lastName: "Welton",
        username: "rebeccawelton",
        profileImg: "https://i.postimg.cc/L8Fc1M6S/rebecca.jpg",
      },
      {
        _id: 103,
        firstName: "Roy",
        lastName: "Kent",
        username: "roykent",
        profileImg: "https://i.postimg.cc/m27HwQR9/roy-kent.jpg",
      },
      {
        _id: 104,
        firstName: "Jamie",
        lastName: "Tartt",
        username: "jamieisawesome",
        profileImg: "https://i.postimg.cc/1zk7VF9m/jamie.jpg",
      },
      {
        _id: 105,
        firstName: "Keeley",
        lastName: "Jones",
        username: "imkeeley",
        profileImg: "https://i.postimg.cc/TwxSHbBk/keeley.jpg",
      },
    ],
    following: [
      {
        _id: 102,
        firstName: "Rebecca",
        lastName: "Welton",
        username: "rebeccawelton",
        profileImg: "https://i.postimg.cc/L8Fc1M6S/rebecca.jpg",
      },
      {
        _id: 103,
        firstName: "Roy",
        lastName: "Kent",
        username: "roykent",
        profileImg: "https://i.postimg.cc/m27HwQR9/roy-kent.jpg",
      },
      {
        _id: 104,
        firstName: "Jamie",
        lastName: "Tartt",
        username: "jamieisawesome",
        profileImg: "https://i.postimg.cc/1zk7VF9m/jamie.jpg",
      },
      {
        _id: 105,
        firstName: "Keeley",
        lastName: "Jones",
        username: "imkeeley",
        profileImg: "https://i.postimg.cc/TwxSHbBk/keeley.jpg",
      },
    ],
    bookmarks: [],
  },
  {
    _id: 102,
    firstName: "Rebecca",
    lastName: "Welton",
    username: "rebeccawelton",
    password: "bossassbitch",
    profileImg: "https://i.postimg.cc/L8Fc1M6S/rebecca.jpg",
    backgroundImg: "https://i.postimg.cc/W31Sx7b1/mswelton-cover.jpg",
    bio: "Owner of Richmond AFC. Also, Boss A** Bitch.",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    followers: [
      {
        _id: 101,
        firstName: "Ted",
        lastName: "Lasso",
        username: "tedlasso",
        profileImg: "https://i.postimg.cc/G2Q8d9s7/ted.png",
      },
      {
        _id: 103,
        firstName: "Roy",
        lastName: "Kent",
        username: "roykent",
        profileImg: "https://i.postimg.cc/m27HwQR9/roy-kent.jpg",
      },
      {
        _id: 104,
        firstName: "Jamie",
        lastName: "Tartt",
        username: "jamieisawesome",
        profileImg: "https://i.postimg.cc/1zk7VF9m/jamie.jpg",
      },
      {
        _id: 105,
        firstName: "Keeley",
        lastName: "Jones",
        username: "imkeeley",
        profileImg: "https://i.postimg.cc/TwxSHbBk/keeley.jpg",
      },
    ],
    following: [
      {
        _id: 101,
        firstName: "Ted",
        lastName: "Lasso",
        username: "tedlasso",
        profileImg: "https://i.postimg.cc/G2Q8d9s7/ted.png",
      },
      {
        _id: 103,
        firstName: "Roy",
        lastName: "Kent",
        username: "roykent",
        profileImg: "https://i.postimg.cc/m27HwQR9/roy-kent.jpg",
      },
      {
        _id: 104,
        firstName: "Jamie",
        lastName: "Tartt",
        username: "jamieisawesome",
        profileImg: "https://i.postimg.cc/1zk7VF9m/jamie.jpg",
      },
      {
        _id: 105,
        firstName: "Keeley",
        lastName: "Jones",
        username: "imkeeley",
        profileImg: "https://i.postimg.cc/TwxSHbBk/keeley.jpg",
      },
    ],
    bookmarks: [],
  },
  {
    _id: 103,
    firstName: "Roy",
    lastName: "Kent",
    username: "roykent",
    password: "roykentawesome",
    profileImg: "https://i.postimg.cc/m27HwQR9/roy-kent.jpg",
    backgroundImg: "https://i.postimg.cc/VL0w3qdg/richmond-afc.jpg",
    bio: "Grrr.",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    followers: [
      {
        _id: 102,
        firstName: "Rebecca",
        lastName: "Welton",
        username: "rebeccawelton",
        profileImg: "https://i.postimg.cc/L8Fc1M6S/rebecca.jpg",
      },
      {
        _id: 101,
        firstName: "Ted",
        lastName: "Lasso",
        username: "tedlasso",
        profileImg: "https://i.postimg.cc/G2Q8d9s7/ted.png",
      },
      {
        _id: 104,
        firstName: "Jamie",
        lastName: "Tartt",
        username: "jamieisawesome",
        profileImg: "https://i.postimg.cc/1zk7VF9m/jamie.jpg",
      },
      {
        _id: 105,
        firstName: "Keeley",
        lastName: "Jones",
        username: "imkeeley",
        profileImg: "https://i.postimg.cc/TwxSHbBk/keeley.jpg",
      },
    ],
    following: [
      {
        _id: 102,
        firstName: "Rebecca",
        lastName: "Welton",
        username: "rebeccawelton",
        profileImg: "https://i.postimg.cc/L8Fc1M6S/rebecca.jpg",
      },
      {
        _id: 101,
        firstName: "Ted",
        lastName: "Lasso",
        username: "tedlasso",
        profileImg: "https://i.postimg.cc/G2Q8d9s7/ted.png",
      },
      {
        _id: 105,
        firstName: "Keeley",
        lastName: "Jones",
        username: "imkeeley",
        profileImg: "https://i.postimg.cc/TwxSHbBk/keeley.jpg",
      },
    ],
    bookmarks: [],
  },
  {
    _id: 104,
    firstName: "Jamie",
    lastName: "Tartt",
    username: "jamieisawesome",
    password: "imthebest14",
    profileImg: "https://i.postimg.cc/1zk7VF9m/jamie.jpg",
    backgroundImg: "https://i.postimg.cc/SNST9kpM/team.jpg",
    bio: "Why be a lion or a panda? I'm me. The best there is.",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    followers: [
      {
        _id: 102,
        firstName: "Rebecca",
        lastName: "Welton",
        username: "rebeccawelton",
        profileImg: "https://i.postimg.cc/L8Fc1M6S/rebecca.jpg",
      },
      {
        _id: 101,
        firstName: "Ted",
        lastName: "Lasso",
        username: "tedlasso",
        profileImg: "https://i.postimg.cc/G2Q8d9s7/ted.png",
      },
      {
        _id: 105,
        firstName: "Keeley",
        lastName: "Jones",
        username: "imkeeley",
        profileImg: "https://i.postimg.cc/TwxSHbBk/keeley.jpg",
      },
    ],
    following: [
      {
        _id: 102,
        firstName: "Rebecca",
        lastName: "Welton",
        username: "rebeccawelton",
        profileImg: "https://i.postimg.cc/L8Fc1M6S/rebecca.jpg",
      },
      {
        _id: 101,
        firstName: "Ted",
        lastName: "Lasso",
        username: "tedlasso",
        profileImg: "https://i.postimg.cc/G2Q8d9s7/ted.png",
      },
      {
        _id: 103,
        firstName: "Roy",
        lastName: "Kent",
        username: "roykent",
        profileImg: "https://i.postimg.cc/m27HwQR9/roy-kent.jpg",
      },
      {
        _id: 105,
        firstName: "Keeley",
        lastName: "Jones",
        username: "imkeeley",
        profileImg: "https://i.postimg.cc/TwxSHbBk/keeley.jpg",
      },
    ],
    bookmarks: [],
  },
  {
    _id: 105,
    firstName: "Keeley",
    lastName: "Jones",
    username: "imkeeley",
    password: "msworldwide",
    profileImg: "https://i.postimg.cc/TwxSHbBk/keeley.jpg",
    backgroundImg: "https://i.postimg.cc/D0yN7TvL/kjpr.jpg",
    bio: "Model turned ✨marketing extraordinaire✨ Find me spying on the boys in the AFC Richmond locker room 😉",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    followers: [
      {
        _id: 102,
        firstName: "Rebecca",
        lastName: "Welton",
        username: "rebeccawelton",
        profileImg: "https://i.postimg.cc/L8Fc1M6S/rebecca.jpg",
      },
      {
        _id: 101,
        firstName: "Ted",
        lastName: "Lasso",
        username: "tedlasso",
        profileImg: "https://i.postimg.cc/G2Q8d9s7/ted.png",
      },
      {
        _id: 103,
        firstName: "Roy",
        lastName: "Kent",
        username: "roykent",
        profileImg: "https://i.postimg.cc/m27HwQR9/roy-kent.jpg",
      },
      {
        _id: 104,
        firstName: "Jamie",
        lastName: "Tartt",
        username: "jamieisawesome",
        profileImg: "https://i.postimg.cc/1zk7VF9m/jamie.jpg",
      },
    ],
    following: [
      {
        _id: 102,
        firstName: "Rebecca",
        lastName: "Welton",
        username: "rebeccawelton",
        profileImg: "https://i.postimg.cc/L8Fc1M6S/rebecca.jpg",
      },
      {
        _id: 101,
        firstName: "Ted",
        lastName: "Lasso",
        username: "tedlasso",
        profileImg: "https://i.postimg.cc/G2Q8d9s7/ted.png",
      },
      {
        _id: 103,
        firstName: "Roy",
        lastName: "Kent",
        username: "roykent",
        profileImg: "https://i.postimg.cc/m27HwQR9/roy-kent.jpg",
      },
      {
        _id: 104,
        firstName: "Jamie",
        lastName: "Tartt",
        username: "jamieisawesome",
        profileImg: "https://i.postimg.cc/1zk7VF9m/jamie.jpg",
      },
    ],
    bookmarks: [],
  },
  {
    _id: 114,
    firstName: "Syed",
    lastName: "Mustassim",
    username: "mustassim",
    password: "mustassim123",
    profileImg: "https://i.postimg.cc/fTYff9yW/urahichi.gif",
    backgroundImg: "https://i.postimg.cc/59ndTr3q/ted-henry.jpg",
    bio: "Every man is the artisan of his own fortune",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    followers: [],
    following: [
      {
        _id: 101,
        firstName: "Ted",
        lastName: "Lasso",
        username: "tedlasso",
        profileImg: "https://i.postimg.cc/G2Q8d9s7/ted.png",
      },
      {
        _id: 102,
        firstName: "Rebecca",
        lastName: "Welton",
        username: "rebeccawelton",
        profileImg: "https://i.postimg.cc/L8Fc1M6S/rebecca.jpg",
      },
    ],
    bookmarks: [],
    portfolio: "https://syedmustassim.com",
  },
];
